const Scenes = {
  splash: 'Splash',
  welcome: 'Welcome',
  login: 'Login',
  register: 'Register',
  home: 'Home',
  player: 'Player',
  library: 'Library',
  radio: 'Radio',
  settings: 'Settings',
  account: 'Account',
  playbackAndHertz: 'PlaybackAndHertz',
  selectLanguage: 'SelectLanguage',
  scanMusic: 'ScanMusic',
  feedback: 'Feedback',
  equalizer: 'Equalizer',
  createPlaylist: 'CreatePlaylist',
  createPlaylistName: 'CreatePlaylistName',
  playlistInside: 'PlaylistInside',
  playlistBrowse: 'PlaylistBrowse',
  playlistSelect: 'PlaylistSelect',
  playlistSelectMusic: 'PlaylistSelectMusic',
  browseArtists: 'BrowseArtists',
};

export default Scenes;
