import { SongItem } from '_stores/songsStore';

export const popularDummySongs: SongItem[] = [
  {
    id: '1',
    title: 'Blinding Lights',
    artists: ['The Weeknd'],
    album: 'After Hours',
    genre: 'Pop',
    duration: 200,
    artwork: null,
    url: 'https://download.samplelib.com/mp3/sample-12s.mp3',
    videoUrl: 'https://download.samplelib.com/mp4/sample-5s.mp4',
    type: 'video',
    isFavorite: false,
  },
  {
    id: '2',
    title: 'Levitating',
    artists: ['Dua Lipa'],
    album: 'Future Nostalgia',
    genre: 'Pop',
    duration: 203,
    artwork:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBTHXxtkDmqIVKH3rpNxMctBR8lMZvnXmD0g&s',
    url: 'https://download.samplelib.com/mp3/sample-12s.mp3',
    videoUrl: null,
    type: 'audio',
    isFavorite: true,
  },
  {
    id: '3',
    title: 'Watermelon Sugar',
    artists: ['Harry Styles'],
    album: 'Fine Line',
    genre: 'Pop',
    duration: 174,
    artwork:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBTHXxtkDmqIVKH3rpNxMctBR8lMZvnXmD0g&s',
    url: 'https://download.samplelib.com/mp3/sample-12s.mp3',
    videoUrl: 'https://download.samplelib.com/mp4/sample-5s.mp4',
    type: 'video',
    isFavorite: false,
  },
  {
    id: '4',
    title: 'Good 4 U',
    artists: ['Olivia Rodrigo'],
    album: 'SOUR',
    genre: 'Pop Rock',
    duration: 178,
    artwork:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBTHXxtkDmqIVKH3rpNxMctBR8lMZvnXmD0g&s',
    url: 'https://download.samplelib.com/mp3/sample-12s.mp3',
    videoUrl: null,
    type: 'radio',
    isFavorite: true,
  },
  {
    id: '5',
    title: 'Montero (Call Me By Your Name)',
    artists: ['Lil Nas X'],
    album: 'Montero',
    genre: 'Hip-Hop',
    duration: 137,
    artwork:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBTHXxtkDmqIVKH3rpNxMctBR8lMZvnXmD0g&s',
    url: 'https://download.samplelib.com/mp3/sample-12s.mp3',
    videoUrl: 'https://download.samplelib.com/mp4/sample-5s.mp4',
    type: 'video',
    isFavorite: false,
  },
  {
    id: '6',
    title: 'Save Your Tears',
    artists: ['The Weeknd'],
    album: 'After Hours',
    genre: 'Pop',
    duration: 215,
    artwork:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBTHXxtkDmqIVKH3rpNxMctBR8lMZvnXmD0g&s',
    url: 'https://download.samplelib.com/mp3/sample-12s.mp3',
    videoUrl: null,
    type: 'audio',
    isFavorite: true,
  },
  {
    id: '7',
    title: 'Peaches',
    artists: ['Justin Bieber', 'Daniel Caesar', 'Giveon'],
    album: 'Justice',
    genre: 'R&B',
    duration: 198,
    artwork:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBTHXxtkDmqIVKH3rpNxMctBR8lMZvnXmD0g&s',
    url: 'https://download.samplelib.com/mp3/sample-12s.mp3',
    videoUrl: 'https://download.samplelib.com/mp4/sample-5s.mp4',
    type: 'video',
    isFavorite: false,
  },
  {
    id: '8',
    title: 'Stay',
    artists: ['The Kid LAROI', 'Justin Bieber'],
    album: 'F*ck Love 3: Over You',
    genre: 'Pop',
    duration: 142,
    artwork:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBTHXxtkDmqIVKH3rpNxMctBR8lMZvnXmD0g&s',
    url: 'https://download.samplelib.com/mp3/sample-12s.mp3',
    videoUrl: null,
    type: 'audio',
    isFavorite: false,
  },
  {
    id: '9',
    title: 'Butter',
    artists: ['BTS'],
    album: 'Butter',
    genre: 'K-Pop',
    duration: 164,
    artwork:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBTHXxtkDmqIVKH3rpNxMctBR8lMZvnXmD0g&s',
    url: 'https://download.samplelib.com/mp3/sample-12s.mp3',
    videoUrl: null,
    type: 'radio',
    isFavorite: true,
  },
  {
    id: '10',
    title: 'Drivers License',
    artists: ['Olivia Rodrigo'],
    album: 'SOUR',
    genre: 'Pop',
    duration: 242,
    artwork:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBTHXxtkDmqIVKH3rpNxMctBR8lMZvnXmD0g&s',
    url: 'https://download.samplelib.com/mp3/sample-12s.mp3',
    videoUrl: 'https://download.samplelib.com/mp4/sample-5s.mp4',
    type: 'video',
    isFavorite: true,
  },
  {
    id: '11',
    title: 'Bad Habits',
    artists: ['Ed Sheeran'],
    album: '=',
    genre: 'Pop',
    duration: 231,
    artwork:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBTHXxtkDmqIVKH3rpNxMctBR8lMZvnXmD0g&s',
    url: 'https://download.samplelib.com/mp3/sample-12s.mp3',
    videoUrl: 'https://download.samplelib.com/mp4/sample-5s.mp4',
    type: 'video',
    isFavorite: false,
  },
  {
    id: '12',
    title: 'Industry Baby',
    artists: ['Lil Nas X', 'Jack Harlow'],
    album: 'Montero',
    genre: 'Hip-Hop',
    duration: 212,
    artwork:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBTHXxtkDmqIVKH3rpNxMctBR8lMZvnXmD0g&s',
    url: 'https://download.samplelib.com/mp3/sample-12s.mp3',
    videoUrl: null,
    type: 'audio',
    isFavorite: true,
  },
  // Repeat the structure for 8 more songs to reach 20.
];
